version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: "easy-cook-postgres"
    hostname: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=chief
      - POSTGRES_PASSWORD=spaghetti
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql